services:
  # Flask Backend
  backend:
    build:
      context: ./app
    container_name: backend
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=yourusername
      - MYSQL_PASSWORD=yourpassword
      - MYSQL_DB=school_management_system
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./app:/app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: school_management_system
      MYSQL_USER: yourusername
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount initialization script

  # Static Frontend (Nginx for serving static files)
  frontend:
    image: nginx:latest
    container_name: static_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
